# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-09 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDePersonasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='file',
            field=models.ImageField(default=-1, upload_to=b''),
            preserve_default=False,
        ),
    ]
