# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaDePersonasApp', '0002_person_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='file',
        ),
        migrations.AddField(
            model_name='personimages',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemaDePersonasApp.Person', verbose_name='propietario de la imagen'),
        ),
    ]
